### ISSUE TITLE
21.line scatter를 생성할 때 y에 적용되는 error가 무엇인지 궁금합니다.

### ISSUE THREAD

**Issue by LaLa4978** [Musalar7/2024Oss-Team-Project---Teylor-series#2]
#본문 내용
21.line에 scatter함수 내부의 y에 들어가는 error가 
None의 의미인지,
라이브러리 내에서 특수한 값을 의미하는지,
error의 값을 따로 선언하는 부분이 없는건지
궁금합니다.

**Comment by kjk0719** [comment]
error 변수 이름을 diff로 수정을 안했었네요 수정하겠습니다
