### ISSUE TITLE
코드의 구현결과를 이해하기 어렵습니다.

### ISSUE THREAD

**Issue by LaLa4978** [Musalar7/2024Oss-Team-Project---Teylor-series#4]
sin(x)함수를 테일러급수로 변환했을 때 sin(x)함수는 제대로 출력되지만
테일러급수는 예상치 못했던 형태로 출력됩니다.
코드의 오류가 있는것은 아닌지 
아니면 제대로 되는 것이 맞는지 주석을 달아주시면 감사하겠습니다.

**Comment by F1R3FIY** [comment]
확인하고 일단 수정해봤습니다
