### ISSUE TITLE
함수 한 번에 합쳐주실 수 있나요?

### ISSUE THREAD

**Issue by 013oz** [Musalar7/2024Oss-Team-Project---Teylor-series#7]
아니면 안 합치고도 실행할 수 있는 방법 같은거 있으면 알려주시면 감사하겠습니다

**Comment by LaLa4978** [comment]
그 따로 repository를 만들어서 실행해야되지 않나요?

**Comment by LaLa4978** [comment]
따로 하나 만든 라이브러리 sample repository가 실제 구현하는 코드들로 채우는 거 아니였나요

**Comment by Musalar7** [comment]
각자 만들걸 가지고 vs code 내에서 함수를 합쳐서 구현까지 확인 한 뒤에 pull로 하면 될 거 같아요

**Comment by Musalar7** [comment]
*push

**Comment by kjk0719** [comment]
함수 호출 부분은 따로 주석처리하여 함수만 작동하도록 올렸어요 나중에 합쳐서 실행하실 때 주석 참고하셔서 넣으시면 될 거 같아요
